<?php

namespace App\Http\Requests\Api;

use Illuminate\Foundation\Http\FormRequest;

class InvoiceRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            // Enviar Correo al Adquiriente
            'send_mail'          => 'nullable|boolean',
            // Document
            'type_document_id'  => ['required','numeric','exists:accounting_documents,id'],
            // Resolution number for document sending
            'resolution_number' => 'required|string',
            'prefix'            => 'nullable|string',
            // Numero de documento
            'document_number'   => 'required|numeric',
            // Date time
            'date' => 'nullable|date_format:Y-m-d',
            'time' => 'nullable|date_format:H:i:s',
            // Notes
            'notes' => 'nullable|string',
            // Tipo operación
            'operation_type_id' => 'nullable|numeric|exists:operation_types,id',
            // Id moneda
            'currency_id'           => 'nullable|integer|exists:currency,id',
            // Cambio de moneda
            'payment_exchange_rate' => 'nullable|array',
            'payment_exchange_rate.exchange_rate'   => 'required_with:exchange_rate|numeric',
            'payment_exchange_rate.rate_date'       => 'required_with:rate_date|date_format:Y-m-d',
            // Payments
            'payments' => 'required:array',
            'payments.*.value_paid'         => 'required:payments.*.value_paid|numeric',
            'payments.*.payment_method_id'  => 'required:payments.*.payment_method_id|exists:payment_methods,id',
            'payments.*.means_payment_id'   => 'required:payments.*.means_payment_id|exists:means_payment,id',
            'payments.*.currency_id'        => 'nullable:payments.*.currency_id|integer|exists:currency,id',
            'payments.*.payment_due_date'   => 'nullable|required_if:payments.*.payment_method_id,=,2|after_or_equal:date|date_format:Y-m-d',
            // Customer
            'customer' => 'nullable|array',
            'customer.dni' => 'nullable|alpha_num|between:1,15',
            'customer.dv' => 'nullable|numeric|digits:1',
            'customer.company_name' => 'nullable|string',
            'customer.identity_document_id' => 'nullable|exists:identity_documents,id',
            'customer.email' => 'nullable:required_with:email|string|email',
            'customer.mobile' => 'nullable:required_with:mobile|numeric|digits_between:7,15',
            'customer.points' => 'nullable:required_with:points|numeric|digits_between:1,10',
            'customer.address' => 'nullable|string',
            'customer.postal_code' => 'nullable:nullable:required_with:mobile|string',
            'customer.city_id'  => 'nullable|exists:cities,id',
            'customer.country_id' => 'nullable|exists:countries,id',
            'customer.type_organization_id' => 'nullable|exists:type_organization,id',
            'customer.tax_regime_id' => 'nullable|exists:tax_regime,id',
            'customer.tax_level_id' => 'nullable|exists:tax_level,id',
            'customer.merchant_registration' => 'nullable|string',
            // Software Manufacturer
            "software_manufacturer" => "nullable|array",
            "software_manufacturer.owner_name" => "nullable|required_if:type_document_id,20|string",
            "software_manufacturer.company_name" => "nullable|required_if:type_document_id,20|string",
            "software_manufacturer.software_name" => "nullable|required_if:type_document_id,20|string",
            // Point of sale
            'point_of_sale' => 'nullable|array',
            'point_of_sale.cashier_name' => 'nullable|required_if:type_document_id,20|string',
            'point_of_sale.terminal_number' => 'nullable|required_if:type_document_id,20|string',
            'point_of_sale.cashier_type' => 'nullable|required_if:type_document_id,20|string',
            'point_of_sale.sales_code' => 'nullable|required_if:type_document_id,20|string',
            'point_of_sale.address' => 'nullable|required_if:type_document_id,20|string',
            'point_of_sale.sub_total' => 'nullable|required_if:type_document_id,20|decimal:2',
            // Discrepancy response
            'discrepancy_response' => 'nullable|array',
            'discrepancy_response.reference_id' => 'nullable|required_with:discrepancy_response|string',
            'discrepancy_response.response_id' => 'nullable|required_with:discrepancy_respon|exists:correction_accounting_notes,id',
            'discrepancy_response.description' => 'nullable|required_with:discrepancy_respon|string',
            // Billing reference
            'billing_reference' => 'nullable|array',
            'billing_reference.number' => 'nullable|required_with:billing_reference|string',
            'billing_reference.date' => 'nullable|required_with:billing_reference|date_format:Y-m-d',
            'billing_reference.uuid' => 'nullable|required_with:billing_reference|string',
            // Order Reference
            'order_reference' => 'nullable|array',
            'order_reference.reference_number' => 'nullable|string',
            'order_reference.reference_date' => 'nullable|date_format:Y-m-d',
            // Allowance charges
            'allowance_charges' => 'nullable|array',
            'allowance_charges.*.charge_indicator' => 'nullable|required_with:allowance_charges|boolean',
            'allowance_charges.*.discount_id' => 'nullable|required_if:allowance_charges.*.charge_indicator,false|exists:discount_codes,id',
            'allowance_charges.*.allowance_charge_reason' => 'nullable|required_with:allowance_charges|string',
            'allowance_charges.*.amount' => 'nullable|required_with:allowance_charges|numeric',
            'allowance_charges.*.base_amount' => 'nullable|required_with:allowance_charges|numeric',
            // Tax totals
            'tax_totals' => 'nullable|array',
            'tax_totals.*.tax_id' => 'nullable|required_with:allowance_charges|exists:taxes,id',
            'tax_totals.*.percent' => 'nullable|required_unless:tax_totals.*.tax_id,10|numeric',
            'tax_totals.*.tax_amount' => 'nullable|required_with:allowance_charges|numeric',
            'tax_totals.*.taxable_amount' => 'nullable|required_with:allowance_charges|numeric',
            'tax_totals.*.quantity_units_id' => 'nullable|required_if:tax_totals.*.tax_id,10|exists:quantity_units,id',
            'tax_totals.*.per_unit_amount' => 'nullable|required_if:tax_totals.*.tax_id,10|numeric',
            'tax_totals.*.base_unit_measure' => 'nullable|required_if:tax_totals.*.tax_id,10|numeric',
            // Tax retentions
            'tax_retentions' => 'nullable|array',
            'tax_retentions.*.tax_id' => 'nullable|exists:taxes,id|numeric',
            'tax_retentions.*.percent' => 'nullable|numeric',
            'tax_retentions.*.tax_amount' => 'nullable|numeric',
            'tax_retentions.*.taxable_amount' => 'nullable|numeric',

            // Prepaid Payment
            'prepaid_payment' => 'nullable|array',
            'prepaid_payment.idpayment' => 'nullable|string',
            'prepaid_payment.paidamount' => 'nullable|numeric',
            'prepaid_payment.receiveddate' => 'nullable|date_format:Y-m-d',
            'prepaid_payment.paiddate' => 'nullable|date_format:Y-m-d',
            'prepaid_payment.instructionid' => 'nullable|string',

            // Legal monetary totals
            'legal_monetary_totals' => 'required|array',
            'legal_monetary_totals.line_extension_amount' => 'required|numeric',
            'legal_monetary_totals.tax_exclusive_amount' => 'required|numeric',
            'legal_monetary_totals.tax_inclusive_amount' => 'required|numeric',
            'legal_monetary_totals.total_allowance' => 'required_with:total_allowance|numeric',
            'legal_monetary_totals.total_charges' => 'required_with:total_charges|numeric',
            'legal_monetary_totals.pre_paid_amount' => 'nullable|required_with:prepaid_payment|numeric',
            'legal_monetary_totals.payable_amount' => 'required|numeric',

            // Invoice lines
            'lines' => 'required|array',
            'lines.*.quantity_units_id' => 'required|exists:quantity_units,id',
            'lines.*.invoiced_quantity' => 'required|numeric',
            'lines.*.line_extension_amount' => 'required|numeric',
            'lines.*.free_of_charge_indicator' => 'required|boolean',
            'lines.*.reference_price_id' => 'nullable|required_if:lines.*.free_of_charge_indicator,true|exists:reference_price,id',
            'lines.*.allowance_charges' => 'nullable|array',
            'lines.*.allowance_charges.*.charge_indicator' => 'nullable|required_with:lines.*.allowance_charges|boolean',
            'lines.*.allowance_charges.*.allowance_charge_reason' => 'nullable|required_with:lines.*.allowance_charges|string',
            'lines.*.allowance_charges.*.amount' => 'nullable|required_with:lines.*.allowance_charges|numeric',
            'lines.*.allowance_charges.*.base_amount' => 'nullable|required_if:lines.*.allowance_charges.*.charge_indicator,false|numeric',
            'lines.*.tax_totals' => 'nullable|array',
            'lines.*.tax_totals.*.tax_id' => 'nullable|required_with:lines.*.tax_totals|exists:taxes,id',
            'lines.*.tax_totals.*.tax_amount' => 'nullable|required_with:lines.*.tax_totals|numeric',
            'lines.*.tax_totals.*.taxable_amount' => 'nullable|required_with:lines.*.tax_totals|numeric',
            'lines.*.tax_totals.*.percent' => 'nullable|required_unless:lines.*.tax_totals.*.tax_id,10|numeric',
            'lines.*.tax_totals.*.quantity_units_id' => 'nullable|required_if:lines.*.tax_totals.*.tax_id,=,10|exists:quantity_units,id',
            'lines.*.tax_totals.*.per_unit_amount' => 'nullable|required_if:lines.*.tax_totals.*.tax_id,10|numeric',
            'lines.*.tax_totals.*.base_unit_measure' => 'nullable|required_if:lines.*.tax_totals.*.tax_id,10|numeric',
            'lines.*.tax_retentions' => 'nullable|array',
            'lines.*.tax_retentions.*.tax_id' => 'nullable|required_with:lines.*.tax_totals|exists:taxes,id',
            'lines.*.tax_retentions.*.tax_amount' => 'nullable|required_with:lines.*.tax_totals|numeric',
            'lines.*.tax_retentions.*.taxable_amount' => 'nullable|required_with:lines.*.tax_totals|numeric',
            'lines.*.tax_retentions.*.percent' => 'nullable|required_unless:lines.*.tax_totals.*.tax_id,10|numeric',
            'lines.*.description' => 'required|string',
            'lines.*.notes' => 'nullable|string',
            'lines.*.code' => 'required|string',
            'lines.*.type_item_identifications_id' => 'required|exists:type_item_identifications,id',
            'lines.*.price_amount' => 'required|numeric',
            'lines.*.base_quantity' => 'required|numeric',
            'lines.*.invoice_period' => 'nullable|array',
            'lines.*.invoice_period.start_date' => 'nullable|required_with:lines.*.invoice_period|date_format:Y-m-d',
            'lines.*.invoice_period.description_code' => 'nullable|required_with:lines.*.invoice_period|exists:ds_invoice_period,id',
        ];
    }
    public function messages(): array
    {
        return [
            'resolution_number.required' => 'El campo resolution_number es requerido',
            'send_mail.boolean' => 'El campo send_mail debe ser booleano',
            'type_document_id.required' => 'El campo type_document_id es requerido',
            'type_document_id.in' => 'El campo type_document_id debe ser 1',
            'type_document_id.exists' => 'El campo type_document_id no existe en la tabla accounting_documents',
            'resolution_number.string' => 'El campo resolution_number debe ser string',
            'document_number.required' => 'El campo document_number es requerido',
            'document_number.string' => 'El campo document_number debe ser string',
            'date.date_format' => 'El campo date debe ser una fecha valida',
            'time.date_format' => 'El campo time debe ser una hora valida',
            'notes.string' => 'El campo notes debe ser string',
            'operation_type_id.numeric' => 'El campo operation_type_id debe ser numérico',
            'operation_type_id.exists' => 'El campo operation_type_id no existe en la tabla operation_types',
            'currency_id.integer' => 'El campo currency_id debe ser numérico',
            'currency_id.exists' => 'El campo currency_id no existe en la tabla currency',
            'payments.array' => 'El campo payments debe ser un arreglo',
            'payments.*.value_paid.required' => 'El campo payments.*.value_paid es requerido',
            'payments.*.value_paid.numeric' => 'El campo payments.*.value_paid debe ser numérico',
            'payments.*.payment_method_id.exists' => 'El campo payments.*.payment_method_id no existe en la tabla payment_methods',
            'payments.*.means_payment_id.exists' => 'El campo payments.*.means_payment_id no existe en la tabla means_payment',
            'payments.*.currency_id.integer' => 'El campo payments.*.currency_id debe ser numérico',
            'payments.*.currency_id.exists' => 'El campo payments.*.currency_id no existe en la tabla currency',
            'payments.*.payment_due_date.after_or_equal' => 'El campo payments.*.payment_due_date debe ser una fecha posterior o igual a la fecha actual',
            'payments.*.payment_due_date.date_format' => 'El campo payments.*.payment_due_date debe ser una fecha valida',
            'customer.required' => 'El campo customer es requerido',
            'customer.array' => 'El campo customer debe ser un arreglo',
            'customer.dni.required' => 'El campo customer.dni es requerido',
            'customer.dni.alpha_num' => 'El campo customer.dni debe ser alfanumérico',
            'customer.dni.between' => 'El campo customer.dni debe tener entre 1 y 15 caracteres',
            'customer.dv.numeric' => 'El campo customer.dv debe ser numérico',
            'customer.dv.digits' => 'El campo customer.dv debe tener 1 digito',
            'customer.company_name.required' => 'El campo customer.company_name es requerido',
            'customer.company_name.string' => 'El campo customer.company_name debe ser string',
            'customer.identity_document_id.exists' => 'El campo customer.identity_document_id no existe en la tabla identity_documents',
            'customer.email.required_unless' => 'El campo customer.email es requerido',
            'customer.email.string' => 'El campo customer.email debe ser string',
            'customer.email.email' => 'El campo customer.email debe ser un correo valido',
            'customer.mobile.required_unless' => 'El campo customer.mobile es requerido',
            'customer.mobile.numeric' => 'El campo customer.mobile debe ser numérico',
            'customer.mobile.digits_between' => 'El campo customer.mobile debe tener entre 7 y 10 caracteres',
            'customer.address.required_unless' => 'El campo customer.address es requerido',
            'customer.address.string' => 'El campo customer.address debe ser string',
            'customer.postal_code.required_unless' => 'El campo customer.postal_code es requerido',
            'customer.postal_code.string' => 'El campo customer.postal_code debe ser string',
            'customer.city_id.required_unless' => 'El campo customer.city_id es requerido',
            'customer.city_id.exists' => 'El campo customer.city_id no existe en la tabla cities',
            'customer.country_id.exists' => 'El campo customer.country_id no existe en la tabla countries',
            'customer.type_organization_id.exists' => 'El campo customer.type_organization_id no existe en la tabla type_organization',
            'customer.tax_regime_id.exists' => 'El campo customer.tax_regime_id no existe en la tabla tax_regime',
            'customer.tax_level_id.exists' => 'El campo customer.tax_level_id no existe en la tabla tax_level',
            'customer.merchant_registration.string' => 'El campo customer.merchant_registration debe ser string',
            'software_manufacturer.array' => 'El campo software_manufacturer debe ser un arreglo',
            'order_reference.array' => 'El campo order_reference debe ser un arreglo',
            'order_reference.reference_number.string' => 'El campo order_reference.reference_number debe ser string',
            'order_reference.reference_date.date_format' => 'El campo order_reference.reference_date debe ser una fecha valida',
            'allowance_charges.array' => 'El campo allowance_charges debe ser un arreglo',
            'allowance_charges.*.charge_indicator.required_with' => 'El campo allowance_charges.*.charge_indicator es requerido',
            'allowance_charges.*.charge_indicator.boolean' => 'El campo allowance_charges.*.charge_indicator debe ser booleano',
            'allowance_charges.*.discount_id.required_if' => 'El campo allowance_charges.*.discount_id es requerido',
            'allowance_charges.*.discount_id.exists' => 'El campo allowance_charges.*.discount_id no existe en la tabla discount_codes',
            'allowance_charges.*.allowance_charge_reason.required_with' => 'El campo allowance_charges.*.allowance_charge_reason es requerido',
            'allowance_charges.*.allowance_charge_reason.string' => 'El campo allowance_charges.*.allowance_charge_reason debe ser string',
            'allowance_charges.*.amount.required_with' => 'El campo allowance_charges.*.amount es requerido',
            'allowance_charges.*.amount.numeric' => 'El campo allowance_charges.*.amount debe ser numérico',
            'allowance_charges.*.base_amount.required_with' => 'El campo allowance_charges.*.base_amount es requerido',
            'allowance_charges.*.base_amount.numeric' => 'El campo allowance_charges.*.base_amount debe ser numérico',
            'tax_totals.array' => 'El campo tax_totals debe ser un arreglo',
            'tax_totals.*.tax_id.required_with' => 'El campo tax_totals.*.tax_id es requerido',
            'tax_totals.*.tax_id.exists' => 'El campo tax_totals.*.tax_id no existe en la tabla taxes',
            'tax_totals.*.tax_amount.required_with' => 'El campo tax_totals.*.tax_amount es requerido',
            'tax_totals.*.tax_amount.numeric' => 'El campo tax_totals.*.tax_amount debe ser numérico',
            'tax_totals.*.taxable_amount.required_with' => 'El campo tax_totals.*.taxable_amount es requerido',
            'tax_totals.*.taxable_amount.numeric' => 'El campo tax_totals.*.taxable_amount debe ser numérico',
            'tax_totals.*.percent.required_unless' => 'El campo tax_totals.*.percent es requerido',
            'tax_totals.*.percent.numeric' => 'El campo tax_totals.*.percent debe ser numérico',
            'tax_totals.*.quantity_units_id.required_if' => 'El campo tax_totals.*.quantity_units_id es requerido',
            'tax_totals.*.quantity_units_id.exists' => 'El campo tax_totals.*.quantity_units_id no existe en la tabla quantity_units',
            'tax_totals.*.per_unit_amount.required_if' => 'El campo tax_totals.*.per_unit_amount es requerido',
            'tax_totals.*.per_unit_amount.numeric' => 'El campo tax_totals.*.per_unit_amount debe ser numérico',
            'tax_totals.*.base_unit_measure.required_if' => 'El campo tax_totals.*.base_unit_measure es requerido',
            'tax_totals.*.base_unit_measure.numeric' => 'El campo tax_totals.*.base_unit_measure debe ser numérico',
            'tax_retentions.array' => 'El campo tax_retentions debe ser un arreglo',
            'tax_retentions.*.tax_id.required_with' => 'El campo tax_retentions.*.tax_id es requerido',
            'tax_retentions.*.tax_id.exists' => 'El campo tax_retentions.*.tax_id no existe en la tabla taxes',
            'tax_retentions.*.tax_amount.required_with' => 'El campo tax_retentions.*.tax_amount es requerido',
            'tax_retentions.*.tax_amount.numeric' => 'El campo tax_retentions.*.tax_amount debe ser numérico',
            'tax_retentions.*.taxable_amount.required_with' => 'El campo tax_retentions.*.taxable_amount es requerido',
            'tax_retentions.*.taxable_amount.numeric' => 'El campo tax_retentions.*.taxable_amount debe ser numérico',
            'tax_retentions.*.percent.required_unless' => 'El campo tax_retentions.*.percent es requerido',
            'tax_retentions.*.percent.numeric' => 'El campo tax_retentions.*.percent debe ser numérico',
            'prepaid_payment.array' => 'El campo prepaid_payment debe ser un arreglo',
            'prepaid_payment.idpayment.string' => 'El campo prepaid_payment.idpayment debe ser string',
            'prepaid_payment.paidamount.numeric' => 'El campo prepaid_payment.paidamount debe ser numérico',
            'prepaid_payment.receiveddate.date_format' => 'El campo prepaid_payment.receiveddate debe ser una fecha valida',
            'prepaid_payment.paiddate.date_format' => 'El campo prepaid_payment.paiddate debe ser una fecha valida',
            'prepaid_payment.instructionid.string' => 'El campo prepaid_payment.instructionid debe ser string',
            'legal_monetary_totals.required' => 'El campo legal_monetary_totals es requerido',
            'legal_monetary_totals.array' => 'El campo legal_monetary_totals debe ser un arreglo',
            'legal_monetary_totals.line_extension_amount.required' => 'El campo legal_monetary_totals.line_extension_amount es requerido',
            'legal_monetary_totals.line_extension_amount.numeric' => 'El campo legal_monetary_totals.line_extension_amount debe ser numérico',
            'legal_monetary_totals.tax_exclusive_amount.required' => 'El campo legal_monetary_totals.tax_exclusive_amount es requerido',
            'legal_monetary_totals.tax_exclusive_amount.numeric' => 'El campo legal_monetary_totals.tax_exclusive_amount debe ser numérico',
            'legal_monetary_totals.tax_inclusive_amount.required' => 'El campo legal_monetary_totals.tax_inclusive_amount es requerido',
            'legal_monetary_totals.tax_inclusive_amount.numeric' => 'El campo legal_monetary_totals.tax_inclusive_amount debe ser numérico',
            'legal_monetary_totals.allowance_total_amount.required' => 'El campo legal_monetary_totals.allowance_total_amount es requerido',
            'legal_monetary_totals.allowance_total_amount.numeric' => 'El campo legal_monetary_totals.allowance_total_amount debe ser numérico',
            'legal_monetary_totals.charge_total_amount.required' => 'El campo legal_monetary_totals.charge_total_amount es requerido',
            'legal_monetary_totals.charge_total_amount.numeric' => 'El campo legal_monetary_totals.charge_total_amount debe ser numérico',
            'legal_monetary_totals.pre_paid_amount.required_with' => 'El campo legal_monetary_totals.pre_paid_amount es requerido',
            'legal_monetary_totals.pre_paid_amount.numeric' => 'El campo legal_monetary_totals.pre_paid_amount debe ser numérico',
            'legal_monetary_totals.payable_amount.required' => 'El campo legal_monetary_totals.payable_amount es requerido',
            'legal_monetary_totals.payable_amount.numeric' => 'El campo legal_monetary_totals.payable_amount debe ser numérico',
            'lines.required' => 'El campo lines es requerido',
            'lines.array' => 'El campo lines debe ser un arreglo',
            'lines.*.quantity_units_id.required' => 'El campo lines.*.quantity_units_id es requerido',
            'lines.*.quantity_units_id.exists' => 'El campo lines.*.quantity_units_id no existe en la tabla quantity_units',
            'lines.*.invoiced_quantity.required' => 'El campo lines.*.invoiced_quantity es requerido',
            'lines.*.invoiced_quantity.numeric' => 'El campo lines.*.invoiced_quantity debe ser numérico',
            'lines.*.line_extension_amount.required' => 'El campo lines.*.line_extension_amount es requerido',
            'lines.*.line_extension_amount.numeric' => 'El campo lines.*.line_extension_amount debe ser numérico',
            'lines.*.free_of_charge_indicator.required' => 'El campo lines.*.free_of_charge_indicator es requerido',
            'lines.*.free_of_charge_indicator.boolean' => 'El campo lines.*.free_of_charge_indicator debe ser booleano',
            'lines.*.reference_price_id.required_if' => 'El campo lines.*.reference_price_id es requerido',
            'lines.*.reference_price_id.exists' => 'El campo lines.*.reference_price_id no existe en la tabla reference_price',
            'lines.*.allowance_charges.array' => 'El campo lines.*.allowance_charges debe ser un arreglo',
            'lines.*.allowance_charges.*.charge_indicator.required_with' => 'El campo lines.*.allowance_charges.*.charge_indicator es requerido',
            'lines.*.allowance_charges.*.charge_indicator.boolean' => 'El campo lines.*.allowance_charges.*.charge_indicator debe ser booleano',
            'lines.*.allowance_charges.*.allowance_charge_reason.required_with' => 'El campo lines.*.allowance_charges.*.allowance_charge_reason es requerido',
            'lines.*.allowance_charges.*.allowance_charge_reason.string' => 'El campo lines.*.allowance_charges.*.allowance_charge_reason debe ser string',
            'lines.*.allowance_charges.*.amount.required_with' => 'El campo lines.*.allowance_charges.*.amount es requerido',
            'lines.*.allowance_charges.*.amount.numeric' => 'El campo lines.*.allowance_charges.*.amount debe ser numérico',
            'lines.*.allowance_charges.*.base_amount.required_if' => 'El campo lines.*.allowance_charges.*.base_amount es requerido',
            'lines.*.allowance_charges.*.base_amount.numeric' => 'El campo lines.*.allowance_charges.*.base_amount debe ser numérico',
            'lines.*.tax_totals.array' => 'El campo lines.*.tax_totals debe ser un arreglo',
            'lines.*.tax_totals.*.tax_id.required_with' => 'El campo lines.*.tax_totals.*.tax_id es requerido',
            'lines.*.tax_totals.*.tax_id.exists' => 'El campo lines.*.tax_totals.*.tax_id no existe en la tabla taxes',
            'lines.*.tax_totals.*.tax_amount.required_with' => 'El campo lines.*.tax_totals.*.tax_amount es requerido',
            'lines.*.tax_totals.*.tax_amount.numeric' => 'El campo lines.*.tax_totals.*.tax_amount debe ser numérico',
            'lines.*.tax_totals.*.taxable_amount.required_with' => 'El campo lines.*.tax_totals.*.taxable_amount es requerido',
            'lines.*.tax_totals.*.taxable_amount.numeric' => 'El campo lines.*.tax_totals.*.taxable_amount debe ser numérico',
            'lines.*.tax_totals.*.percent.required_unless' => 'El campo lines.*.tax_totals.*.percent es requerido',
            'lines.*.tax_totals.*.percent.numeric' => 'El campo lines.*.tax_totals.*.percent debe ser numérico',
            'lines.*.tax_totals.*.quantity_units_id.required_if' => 'El campo lines.*.tax_totals.*.quantity_units_id es requerido',
            'lines.*.tax_totals.*.quantity_units_id.exists' => 'El campo lines.*.tax_totals.*.quantity_units_id no existe en la tabla quantity_units',
            'lines.*.tax_totals.*.per_unit_amount.required_if' => 'El campo lines.*.tax_totals.*.per_unit_amount es requerido',
            'lines.*.tax_totals.*.per_unit_amount.numeric' => 'El campo lines.*.tax_totals.*.per_unit_amount debe ser numérico',
            'lines.*.tax_totals.*.base_unit_measure.required_if' => 'El campo lines.*.tax_totals.*.base_unit_measure es requerido',
            'lines.*.tax_totals.*.base_unit_measure.numeric' => 'El campo lines.*.tax_totals.*.base_unit_measure debe ser numérico',
            'lines.*.tax_retentions.array' => 'El campo lines.*.tax_retentions debe ser un arreglo',
            'lines.*.tax_retentions.*.tax_id.required_with' => 'El campo lines.*.tax_retentions.*.tax_id es requerido',
            'lines.*.tax_retentions.*.tax_id.exists' => 'El campo lines.*.tax_retentions.*.tax_id no existe en la tabla taxes',
            'lines.*.tax_retentions.*.tax_amount.required_with' => 'El campo lines.*.tax_retentions.*.tax_amount es requerido',
            'lines.*.tax_retentions.*.tax_amount.numeric' => 'El campo lines.*.tax_retentions.*.tax_amount debe ser numérico',
            'lines.*.tax_retentions.*.taxable_amount.required_with' => 'El campo lines.*.tax_retentions.*.taxable_amount es requerido',
            'lines.*.tax_retentions.*.taxable_amount.numeric' => 'El campo lines.*.tax_retentions.*.taxable_amount debe ser numérico',
            'lines.*.tax_retentions.*.percent.required_unless' => 'El campo lines.*.tax_retentions.*.percent es requerido',
            'lines.*.tax_retentions.*.percent.numeric' => 'El campo lines.*.tax_retentions.*.percent debe ser numérico',
            'lines.*.description.required' => 'El campo lines.*.description es requerido',
            'lines.*.description.string' => 'El campo lines.*.description debe ser string',
            'lines.*.notes.string' => 'El campo lines.*.notes debe ser string',
            'lines.*.code.required' => 'El campo lines.*.code es requerido',
            'lines.*.code.string' => 'El campo lines.*.code debe ser string',
            'lines.*.type_item_identifications_id.required' => 'El campo lines.*.type_item_identifications_id es requerido',
            'lines.*.type_item_identifications_id.exists' => 'El campo lines.*.type_item_identifications_id no existe en la tabla type_item_identifications',
            'lines.*.price_amount.required' => 'El campo lines.*.price_amount es requerido',
            'lines.*.price_amount.numeric' => 'El campo lines.*.price_amount debe ser numérico',
            'lines.*.base_quantity.required' => 'El campo lines.*.base_quantity es requerido',
            'lines.*.base_quantity.numeric' => 'El campo lines.*.base_quantity debe ser numérico',
        ];
    }
}
