/**
 * Estado del documento para las facturas.
 *
 * @enum {string}
 */
export enum DocumentStatusEnum {
	DRAFT = 'DRAFT',
	SENT = 'SENT',
	OVERDUE = 'OVERDUE',
	PAID = 'PAID',
	PARTIALLY_PAID = 'PARTIALLY_PAID',
	CANCELLED = 'CANCELLED',
	REJECTED = 'REJECTED',
	DISPUTED = 'DISPUTED',
	REFUNDED = 'REFUNDED',
	ON_HOLD = 'ON_HOLD',
	DEFINITIVE = 'DEFINITIVE',
	CLOSED = 'CLOSED',
	OPEN = 'OPEN',
	DELETED = 'DELETED',
	PENDING = 'PENDING',
	ANNULLED = 'ANNULLED',
	ACCEPTED = 'ACCEPTED',
	PROCESSING = 'PROCESSING',
	ACCOUNTED = 'ACCOUNTED',
	PROCESSED = 'PROCESSED',
	UNKNOWN = 'UNKNOWN',
	ABIERTO = 'ABIERTO',
	ANULADO = 'ANULADO',
	APROBADO = 'APROBADO',
	CERRADO = 'CERRADO',
	CONCILIADO = 'CONCILIADO',
	CONCILIATION = 'CONCILIATION',
	CONFIRMADO = 'CONFIRMADO',
	ACEPTADO = 'ACEPTADO',
	PROCESANDO = 'PROCESANDO',
	DESCONOCIDO = 'DESCONOCIDO',
}

/**
 * Estado del documento para las facturas.
 *
 * @enum {string}
 */
export enum DocumentTestStatusEnum {
	CREATED = 'CREATED',
	RUNNING = 'RUNNING',
	VALIDATING = 'VALIDATING',
	FINISHED = 'FINISHED',
	ERROR = 'ERROR',
	SENDING = 'SENDING',
	UNKNOWN = 'UNKNOWN',
}
