export enum ViafirmaInternalStateEnum {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  POLLING = 'POLLING',
  READY_TO_DOWNLOAD = 'READY_TO_DOWNLOAD',
  DOWNLOADED = 'DOWNLOADED',
  ASSEMBLED = 'ASSEMBLED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  FAILED_RECOVERABLE = 'FAILED_RECOVERABLE',
  EXPIRED = 'EXPIRED',
}
